export { apiClient, handleApiError } from './api';
export { queryClient } from './queryClient';
export type { ApiError } from './api';
export { authService } from './auth';
export { taskService } from './task';
export { categoryService } from './category';
export { deckService } from './deck';
export { bookService } from './book';
export { gamificationService } from './gamification';
export { dictionaryService } from './dictionary';
export type { DictionaryEntry, DictionaryMeaning } from './dictionary';
